### PR TITLE
CFS and ELF loader

### PR DESCRIPTION
**Pull request by kYc0o**
Support for CFS (Contiki File System) and ELF loader in iotlab-m3 platform

### CODE REVIEW

**Comment by cladmi** [comment]
Thank you your work. I will test your code on the https://github.com/iot-lab/contiki/tree/cfs_and_elf_loader' branch 
But beware this branch will have it's history rewritten.

**Comment by cladmi** [comment]
I'm currently finishing to package CFS stuff, can I keep the 'inti console' or is there a reason why you removed it?

**Comment by kYc0o** [comment]
It was an example to push files to nodes using the serial link (through ssh) in a similar way that sky-shell does. If you consider that the example is useful you can keep it.

**Comment by cladmi** [comment]
I'm using it for testing so I will package it with the release.

**Comment by cladmi** [comment]
I pushed the CFS support: https://github.com/iot-lab/contiki/commit/bea4b6fd738ebc61d45ea8f6736e447feb2f509e

I changed the n25xxx functions calls, and also added `watchdog_periodic();` calls when formating in `xmem_erase` function. Either the node would reboot after 36 sectors during format.

Either than that, only whitespaces formatting and history rewriting.

Thank for your work.

I will wait to be back at work, I think, to test the elf loader stuff.

**Comment by cladmi** [comment]
For the moment I can't get  the elfloader to work. I tried to load the blinking led example but it can't find symbol 'leds_toggle'. And in fact, it's not present in `symbol.c` and the final firmware:

```
┌─[harter@mercator][~/work/iot-lab/parts/contiki/examples/iotlab/06-shell-cfs-elfloader][10:46:35][0]$
└─o nm console_server.iotlab-m3  | grep leds_toggle
```
However I can find it in `contiki.iotlab-m3.a`
```
┌─[harter@mercator][~/work/iot-lab/parts/contiki/examples/iotlab/06-shell-cfs-elfloader][10:46:39][1]$
└─o nm contiki-iotlab-m3.a | grep leds_toggle
         U leds_toggle
         U leds_toggle
00000089 T leds_toggle
```

However the link command shouldn't remove the symbols:

    arm-none-eabi-gcc -nostartfiles -nodefaultlibs -T../../../../openlab/platform/scripts/stm32f103rey6.ld -mcpu=cortex-m3 -mthumb -mthumb-interwork  console_server.co \
	    contiki-iotlab-m3.a  -o console_server.iotlab-m3

**Comment by cladmi** [comment]
Do you had any problem with this also?

I think we should adapt the 'symbol.c' generation to extract the symbols of all the linked files instead of just the final firmware, more like what's done in `cooja`

**Comment by kYc0o** [comment]
Hi! Sorry I wasn't in the office this morning.

Yes, I have the same problem in every firmware that I want to prepare for dynamic loading.
I tried with several flags for gcc and the __attribute__((used)) feature without sucess.

What I am doing now is a fake call to the symbol that I want to include.

How do you think we can force to include all functions in the base firmware?

The "hello-world" example was the first I tried and it works well. Did ou try it?

Thanks for your work!

**Comment by cladmi** [comment]
In my current state it does not work but as I tried many things I may have broken it.

```
loadelf hello-world.ce
..... # verbose output of elfloader and elfloader-arch
Result of loading 5
Symbol not found: '#'       # I added debug infos
```
I will try to fix it again for hello-world.

I'm at this point here for the moment:

https://github.com/iot-lab/contiki/compare/iot-lab:master...cfs_and_elf_loader


Regarding the missing symbols, I once tried yesterday to manually add `leds.o` in the command that generated `symbols.c` and all the subsequent `make` calls had the `leds_toggle` so I think we should find a way to add everything to `symbols.c` has they will be kept when linking the final executable.

I just tried to use `contiki.iotlab-m3.a` to generate the symbols.c but got many `undefined references` when building the final executable.

After adding leds.o it failed with error 7 instead of 5 https://github.com/contiki-os/contiki/wiki/The-dynamic-loader but has I didn't investigated any longer on this for the moment.

**Comment by cladmi** [comment]
I'm also wondering if it's because `leds_toggle` is just a random function in a C file which is not wrapped by any Contiki specific structure.

On a real system, only the system libraries are available so `leds_toggle` might the bad exception.

**Comment by kYc0o** [comment]
Notice that the ELF file is modified every time that elfloader_load() is called, so you need to make a copy of the file or remove it and upload a new .ce file.

I will make the tests in that branch.

**Comment by cladmi** [comment]
About hello-world.ce, I distclean and recompiled and no more symbol errors but it's failing with error '7'.

**Comment by kYc0o** [comment]
I tried your example and the .ce file lacks the "autostart_processes" symbol. Did you modified the Makefile to generate the .ce file? That's why you're getting the error 7

**Comment by cladmi** [comment]
My fault, when generating the `.ce` file I try cleaning up by using the regular c -> o rule which lacks the '-DAUTOSTART_ENABLE' you added. I will fix this and push-force.

**Comment by cladmi** [comment]
Now it's loading but not doing anything:

```
> loadelf hello-world.ce
Result of loading 0
> ls
File: hello-world.ce (1354 bytes)
> 
```

**Comment by kYc0o** [comment]
I think you need to autostart the process, with something like this (from shell-exec.c) : 
```
if(ret == ELFLOADER_OK) {
      int i;
      for(i = 0; elfloader_autostart_processes[i] != NULL; ++i) {
	shell_output_str(&exec_command, "exec: starting process ",
			 elfloader_autostart_processes[i]->name);
      }
      autostart_start(elfloader_autostart_processes);
    }
```

**Comment by cladmi** [comment]
Yeah this makes it work! Thank you. I will clean the code, document this and come back for a final review.

Can you just tell me why the file is modified on `elfloader_load` to add in the documentation.

**Comment by cladmi** [comment]
The `hello world` example is maybe not the best to demonstrate as by default, it just echoes the command and print a `>`, which is quite the same as the loader firmware.
I added  some stuff around to make it more visible.

```
Platform starting in 1... 
GO!
[in clock_init() DEBUG] Starting systick timer at 100Hz
 Starting 'Console_server'
Console server started !
ls
File: hello-world.ce (1354 bytes)
> rm hello-world.ce
> upload hello-world.ce
Uploading file hello-world.ce
File uploaded (1356 bytes)
> loadelf hello-world.ce
Result of loading 0
exec: starting process Serial Echo
Hello World !
> ls
> Hello World !
Echo cmd: 'ls'
> File: hello-world.ce (1354 bytes)
> 
```

**Comment by kYc0o** [comment]
OK great! In fact the console example wasn't in the las version (a commit that was never made, it's a colleague's work, we can thank him!). I will commit the new file with the chages for the loadelf command.

**Comment by kYc0o** [comment]
Voilà! https://github.com/kYc0o/contiki/commit/1384337c706f4a6a52e8885a14ea7fcf0f77dd75

**Comment by cladmi** [comment]
I just tried to merge everything in 3 commits for each change: 

https://github.com/iot-lab/contiki/pull/3

It would be great if you could do a final review of the code, I will merge it afterwards as it's in a working state.

Thank you for all your work.

**Comment by kYc0o** [comment]
Everything seems ok for me, maybe a clean-up for  ```elfloader-arch.c``` would be good to respect the memory size allowed by ```ELFLOADER_CONF_TEXTMEMORY_SIZE```. For now the aligned text memory is set to 8K. (line 72 of ```elfloader-arch.c```). I will try to do it but it will not be soon...

Thanks to you too, you made a great work merging the pull request.

**Comment by cladmi** [comment]
I will merge it in this state, the remaining will be considerer improvements.

**Pull request closed without merging**
